name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to API EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_API_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/distributed-job-queue
            git pull origin main
            npm install
            cd dashboard
            npm install
            npm run build
            cd ..
            npx prisma generate
            pm2 restart api --update-env
            pm2 save

  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Worker EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_WORKER_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/distributed-job-queue
            git pull origin main
            npm install
            npx prisma generate
            pm2 restart worker --update-env
            pm2 save
